# Generated by Django 5.1.4 on 2026-05-28 10:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyquiz',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='dailyquiz',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='dailyquiz',
            name='is_published',
        ),
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('true_false', 'True/False'), ('multiple_choice', 'Multiple choice')], default='true_false', max_length=20),
        ),
        migrations.AddField(
            model_name='quizanswer',
            name='selected_bool',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_index',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='question',
            name='options',
            field=models.JSONField(blank=True, help_text='Multiple-choice only: list of exactly 4 non-empty strings.', null=True),
        ),
        migrations.AlterField(
            model_name='quizanswer',
            name='selected_index',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.CreateModel(
            name='AttemptQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='served_questions', to='quizzes.quizattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempt_servings', to='quizzes.question')),
            ],
            options={
                'db_table': 'attempt_questions',
                'ordering': ['position'],
            },
        ),
        migrations.DeleteModel(
            name='DailyQuizQuestion',
        ),
        migrations.AddConstraint(
            model_name='attemptquestion',
            constraint=models.UniqueConstraint(fields=('attempt', 'position'), name='unique_attempt_position'),
        ),
        migrations.AddConstraint(
            model_name='attemptquestion',
            constraint=models.UniqueConstraint(fields=('attempt', 'question'), name='unique_attempt_question_served'),
        ),
    ]
