# Generated by Django 5.1.4 on 2026-05-30 11:35

import secrets
import string

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_verification_codes(apps, schema_editor):
    """Assign a unique 8-char code to every project created before this field."""
    Project = apps.get_model('projects', 'Project')
    alphabet = string.ascii_uppercase + string.digits
    used = set(
        Project.objects.exclude(verification_code__isnull=True)
        .values_list('verification_code', flat=True)
    )
    for project in Project.objects.filter(verification_code__isnull=True):
        while True:
            code = ''.join(secrets.choice(alphabet) for _ in range(8))
            if code not in used:
                used.add(code)
                break
        project.verification_code = code
        project.save(update_fields=['verification_code'])


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='points_reward',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='verification_code',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
        migrations.RunPython(
            backfill_verification_codes,
            migrations.RunPython.noop,
        ),
        migrations.CreateModel(
            name='ProjectCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='projects.project')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_completions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'project_completions',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('project', 'student'), name='unique_project_student')],
            },
        ),
    ]
