# Generated by Django 5.1.4 on 2026-02-20 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_firebase_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stars',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
