# Generated by Django 5.1.4 on 2026-03-10 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_stars_alter_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='stars',
            new_name='points',
        ),
    ]
