# Generated by Django 5.1.4 on 2026-05-27 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_stars_user_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='school',
            field=models.CharField(blank=True, choices=[('energy_petroleum', 'School of Energy and Petroleum Industry'), ('geology', 'School of Geology'), ('it_engineering', 'School of Information Technology and Engineering'), ('business', 'Business School'), ('intl_economics', 'International School of Economics'), ('maritime', 'Kazakhstan Maritime Academy'), ('applied_math', 'School of Applied Mathematics'), ('chem_engineering', 'School of Chemical Engineering'), ('social_sciences', 'School of Social Sciences'), ('materials_green', 'School of Materials Science and Green Technologies')], max_length=32, null=True),
        ),
    ]
