# Generated by Django 5.1.4 on 2026-07-08 13:36

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('condition_type', models.CharField(choices=[('total_xp', 'Total XP'), ('level', 'Level'), ('streak', 'Streak'), ('completions', 'Completions'), ('daily_completions', 'Daily completions'), ('weekly_completions', 'Weekly completions'), ('single_action_xp', 'Single action XP'), ('special', 'Special')], default='special', max_length=30)),
                ('condition_value', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'challenge_badges',
                'ordering': ['condition_type', 'condition_value'],
            },
        ),
        migrations.CreateModel(
            name='EcoLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_number', models.PositiveSmallIntegerField(unique=True)),
                ('title', models.CharField(max_length=100)),
                ('required_xp', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'challenge_levels',
                'ordering': ['level_number'],
            },
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', max_length=20)),
                ('category', models.CharField(choices=[('transport', 'Transport'), ('waste', 'Waste'), ('energy', 'Energy'), ('activity', 'Activity'), ('campus', 'Campus'), ('other', 'Other')], default='other', max_length=20)),
                ('base_xp', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('verification_type', models.CharField(choices=[('none', 'No evidence'), ('camera_photo', 'Camera photo'), ('screenshot', 'Screenshot')], default='none', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'challenges',
                'ordering': ['frequency', 'category', 'title'],
                'indexes': [models.Index(fields=['frequency', 'is_active'], name='challenges_frequen_a0249f_idx'), models.Index(fields=['category'], name='challenges_categor_e15c90_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChallengeTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('captain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captained_challenge_teams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'challenge_teams',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ChallengeTeamMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('captain', 'Captain'), ('member', 'Member')], default='member', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='challenges.challengeteam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_team_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'challenge_team_memberships',
                'ordering': ['joined_at'],
            },
        ),
        migrations.AddField(
            model_name='challengeteam',
            name='members',
            field=models.ManyToManyField(related_name='challenge_teams', through='challenges.ChallengeTeamMembership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='EcoProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_xp', models.PositiveIntegerField(default=0)),
                ('current_level', models.PositiveSmallIntegerField(default=1)),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('longest_streak', models.PositiveIntegerField(default=0)),
                ('last_completed_date', models.DateField(blank=True, null=True)),
                ('completed_challenges_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eco_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'eco_profiles',
                'ordering': ['-total_xp'],
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_by', to='challenges.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eco_badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_challenge_badges',
                'ordering': ['-earned_at'],
            },
        ),
        migrations.CreateModel(
            name='ChallengeCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('evidence_image', models.ImageField(blank=True, null=True, upload_to='challenge_evidence/%Y/%m/%d/')),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=20)),
                ('base_xp', models.PositiveIntegerField(default=0)),
                ('streak_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=4)),
                ('xp_awarded', models.PositiveIntegerField(default=0)),
                ('streak_day', models.PositiveIntegerField(default=0)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='challenges.challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_completions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'challenge_completions',
                'ordering': ['-completed_at'],
                'indexes': [models.Index(fields=['user', 'period_start'], name='challenge_c_user_id_d2d541_idx'), models.Index(fields=['challenge', 'period_start'], name='challenge_c_challen_9af1a9_idx'), models.Index(fields=['status'], name='challenge_c_status_87bcad_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'challenge', 'period_start'), name='unique_challenge_completion_per_period')],
            },
        ),
        migrations.AddConstraint(
            model_name='challengeteammembership',
            constraint=models.UniqueConstraint(fields=('team', 'user'), name='unique_challenge_team_member'),
        ),
        migrations.AddConstraint(
            model_name='userbadge',
            constraint=models.UniqueConstraint(fields=('user', 'badge'), name='unique_user_challenge_badge'),
        ),
    ]
