"""
Use-case layer for the ``shop`` app.

Points-debit, refund, and promo-code redemption flows live here — the view
layer is responsible only for HTTP parsing and serialisation. Keeping the
state machine and the balance update together inside :func:`~django.db.transaction.atomic`
means Django admin actions, management commands, and future Celery retries
can call the exact same code path that the REST endpoints call.
"""
from __future__ import annotations

import hmac

from django.db import transaction
from django.db.models import F

from apps.core.exceptions import (
    InsufficientPointsError,
    InvalidStateTransitionError,
    InvalidVerificationCodeError,
    ShopInactiveError,
)
from apps.users.models import User

from .models import Purchase, Shop, ShopItem


@transaction.atomic
def purchase_item(*, user: User, item: ShopItem) -> Purchase:
    """Debit ``item.price`` from ``user.points`` and create a ``Purchase``.

    A ``PENDING`` purchase is created for internal shops (the owner confirms
    delivery in-person) and a ``READY`` purchase for external shops (a promo
    code is auto-generated by ``Purchase.save`` for in-person redemption).

    Raises:
        ShopInactiveError: the parent shop is deactivated.
        InsufficientPointsError: the user's balance is below ``item.price``.
    """
    if not item.shop.is_active:
        raise ShopInactiveError('This shop is currently inactive.')

    # Lock the user row before reading ``points`` to avoid a lost-update race
    # when two concurrent requests spend from the same balance.
    locked_user = User.objects.select_for_update().get(pk=user.pk)
    if locked_user.points < item.price:
        raise InsufficientPointsError(
            'You do not have enough points for this purchase.'
        )

    User.objects.filter(pk=locked_user.pk).update(
        points=F('points') - item.price,
    )

    initial_status = (
        Purchase.Status.PENDING
        if item.shop.shop_type == Shop.Type.INTERNAL
        else Purchase.Status.READY
    )
    purchase = Purchase(
        student=locked_user,
        item=item,
        points_spent=item.price,
        status=initial_status,
    )
    purchase.save()
    return purchase


@transaction.atomic
def confirm_or_reject_purchase(
    *, purchase: Purchase, new_status: str,
) -> Purchase:
    """Resolve an internal-shop ``PENDING`` purchase.

    On ``REJECTED`` the points are refunded to the student; on ``COMPLETED``
    no balance change is needed (points were debited at purchase time).

    Raises:
        InvalidStateTransitionError: transition not allowed from current state.
    """
    locked = Purchase.objects.select_for_update().get(pk=purchase.pk)
    if not locked.can_transition_to(new_status):
        raise InvalidStateTransitionError(
            f"Cannot change status from '{locked.status}' to '{new_status}'."
        )
    locked.status = new_status
    locked.save(update_fields=['status', 'updated_at'])

    if new_status == Purchase.Status.REJECTED:
        User.objects.filter(pk=locked.student_id).update(
            points=F('points') + locked.points_spent,
        )
    return locked


@transaction.atomic
def redeem_promo_code(*, shop: Shop, code: str) -> Purchase:
    """Mark an external-shop ``READY`` purchase as ``COMPLETED``.

    The purchase is located by ``(promo_code, shop, status=READY)`` under a
    row lock so a concurrent redemption cannot double-spend the same code.
    A constant-time compare is then applied to the fetched value as
    defence-in-depth against timing attacks on the unique-index probe.

    Raises:
        InvalidVerificationCodeError: no matching ready purchase for this shop.
    """
    try:
        purchase = (
            Purchase.objects
            .select_for_update()
            .get(
                promo_code=code,
                item__shop=shop,
                status=Purchase.Status.READY,
            )
        )
    except Purchase.DoesNotExist as exc:
        raise InvalidVerificationCodeError(
            'Invalid or already used promo code.'
        ) from exc

    if not hmac.compare_digest(purchase.promo_code or '', code):
        raise InvalidVerificationCodeError(
            'Invalid or already used promo code.'
        )

    purchase.status = Purchase.Status.COMPLETED
    purchase.save(update_fields=['status', 'updated_at'])
    return purchase
